In [2]:
import numpy as np
import datetime

In [7]:
a = np.eye(11)
print a.size
b = np.array([[1, 2], [3, 4], [5, 6]])
print b
print b[:,0].sum()
arrays = []
arrays.append(a)
arrays.append(b)
print arrays
b = np.delete(b,2,0)
print b

121
[[1 2]
 [3 4]
 [5 6]]
9
[array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]]), array([[1, 2],
       [3, 4],
       [5, 6]])]
[[1 2]
 [3 4]]


In [24]:
#Rules
#sum of all rows must equal 1
for i in range(2):
    print b[i,:]

[1 2]
[3 4]


In [39]:
#create base array and take all combinations to make a larger array
eye = np.eye(11)
for i in range(11):
    print eye, eye[0]
    eye = np.delete(eye, (10-i), 0)

 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]] [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0

In [37]:
print datetime.datetime.now()
arrays = []
eye = np.eye(11)
for a in range(11):
    matrix = np.zeros((11,11))
    matrix[0] = eye[a]
    eye_a = np.delete(eye, a, 0)
    for b in range(10):
        print a,b
        matrix[1] = eye_a[b]
        eye_b = np.delete(eye_a, b, 0)
        for c in range(9):
            matrix[2] = eye_b[c]
            eye_c = np.delete(eye_b, c, 0)
            for d in range(8):
                matrix[3] = eye_c[d]
                eye_d = np.delete(eye_c, d, 0)
                for e in range(7):
                    matrix[4] = eye_d[e]
                    eye_e = np.delete(eye_d, e, 0)
                    for f in range(6):
                        matrix[5] = eye_e[f]
                        eye_f = np.delete(eye_e, f, 0)
                        for g in range(5):
                            matrix[6]= eye_f[g]
                            eye_g = np.delete(eye_f, g, 0)
                            for h in range(4):
                                matrix[7] = eye_g[h]
                                eye_h = np.delete(eye_g, h, 0)
                                for i in range(3):
                                    matrix[8] = eye_h[i]
                                    eye_i = np.delete(eye_h, i, 0)
                                    for j in range(2):
                                        matrix[9] = eye_i[j]
                                        eye_j = np.delete(eye_i, j, 0)
                                        matrix[10] = eye_j[0]
print datetime.datetime.now()
print len(arrays)
print matrix

2016-12-27 00:18:25.158000
0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 0
3 1
3 2
3 3
3 4
3 5


KeyboardInterrupt: 